branches:
  only:
  - gh-pages


language: node_js
node_js: "node"


before_deploy:
  - npm run unpack-data
  - npm run prepare-site
  
deploy:
  skip_cleanup: true
  provider: surge
  domain: stock-data.surge.sh
  on:
    branch: gh-pages

