branches:
  only:
  - json


language: node_js
node_js: "node"


before_deploy:
  - npm run release
  
deploy:
  skip_cleanup: true
  provider: surge
  domain: stock-data.surge.sh
  on:
    branch: json

