branches:
  only:
  - gh-pages


language: node_js
node_js: "node"


before_deploy:
  - for f in $(find -maxdepth 1 | grep .tar.gz); do mkdir ${f%.tar.gz}; tar -xafvz $f -C ${f%.tar.gz} ; done
  - cd 2015
  - ls
  - cd ../2016
  - ls
  - rm CNAME
  
deploy:
  skip_cleanup: true
  provider: surge
  domain: stock-data.surge.sh
  on:
    branch: gh-pages

