branches:
  only:
  - gh-pages


language: node_js
node_js: "node"


before_deploy:
  - rm CNAME
  - for f in $(find . | grep .tar.gz); do mkdir ${f%.tar.gz}; tar -xaf $f -C ${f%.tar.gz}; rm $f ; done
  - echo "<center><h2>pystock data raw<h2><br><i>files:</i><br><tt>" > index.html 
  - for f in $(find . -type f | sort -nr| grep 20); do echo "<a href='$f'>$f</a><br>" >> index.html; done

  
deploy:
  skip_cleanup: true
  provider: surge
  domain: stock-data.surge.sh
  on:
    branch: gh-pages

